image:
    file: .gitpod.Dockerfile
tasks:
    - name: Shopware
      before: |
        echo 'alias admin-watch="LOAD_DOTENV=0 APP_URL=http://localhost:8000 ./bin/watch-administration.sh"' >> ~/.bashrc
      init: |
        # Run MySQL
        docker run --restart always -d --name=mysql -v /workspace/mysql:/var/lib/mysql -p 127.0.0.1:3306:3306 -e MYSQL_ROOT_PASSWORD=root mysql:8
        docker run --restart always -d --name=adminer --link mysql:mysql -p 5000:8080 -e ADMINER_DESIGN=pepa-linha -e ADMINER_DEFAULT_SERVER=mysql -e ADMINER_PLUGINS="tables-filter table-structure json-column version-noverify" ghcr.io/shyim/shopware-docker/adminer

        touch .env.local
        echo "DATABASE_URL="mysql://root:root@127.0.0.1:3306/shopware"" >> .env.local
        echo "TRUSTED_PROXIES=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16" >> .env.local
        echo "APP_URL=""" >> .env.local
        echo "SHELL_VERBOSITY=0" >> .env.local
        
        eval $(gp env -e) # is this needed?
        composer config bearer.packages.shopware.com ${SHOPWARE_PACKAGES_SECRET}

        composer config --global github-oauth.github.com $(printf '%s\n' host=github.com | gp credential-helper get | sort | head -2 | tail -1 | sed 's;password=;;')
        
        composer install

        test -f install.lock && rm install.lock
        ./bin/console system:install --basic-setup --create-database --drop-database

        ./bin/console system:config:set core.frw.completedAt '2019-10-07T10:46:23+00:00'

        #./bin/console framework:demodata --products 300
        #echo "CREATE DATABASE shopware" | mysql -u root --password=root
        #mysql -u root --password=root shopware < dump.sql
        #./bin/console dal:refresh:index

        ./bin/console system:generate-jwt-secret -f
        ./bin/console system:generate-app-secret
        ./bin/console theme:compile
        ./bin/build-administration.sh
        ./bin/build-storefront.sh

        rm -rf var/cache/*

        # Set by default to dev
        sed -i -e "s;APP_ENV=.*$;APP_ENV=dev;" .env
      command: |
        # Gitpod registers the ports on first docker command
        docker ps

        # Wait for port open
        gp ports await 3306

        # Wait until MySQL is reachable
        until mysqladmin ping; do
            sleep 1
        done

        # Update domain url
        ./bin/console sales-channel:update:domain $(gp url 8000 | awk -F[/:] '{print $4}')

        # Start Webserver
        symfony server:start --port 8000 -d
    - name: Getting Started
      command: |
        echo 'Hey!. Your environment is starting soon. You can see the progress in the Shopware Terminal'
        echo 'If you want to run the Admin Watch, just use the Terminal alias: admin-watch'
        echo 'Happy Coding!'
        echo "Shop URL: $(gp url 8000)"
        echo "Admin-Watcher URL: $(gp url 8080)"
        echo "Adminer URL: $(gp url 5000)"
ports:
    - port: 8000
      visibility: private
      description: Shopware
      onOpen: open-browser
    - port: 5000
      visibility: private
      description: Adminer
      onOpen: notify
    - name: Admin-Watcher
      port: 8080
      onOpen: notify
      description: "Use Forward Proxy to localhost to access this service"
jetbrains:
    phpstorm:
        plugins:
            - de.espend.idea.php.annotation
            - fr.adrienbrault.idea.symfony2plugin
            - de.shyim.shopware6
            - de.shyim.ideaphpstantoolbox
        vmoptions: "-Xmx4g"
        prebuilds:
            version: stable
vscode:
    extensions:
        - bmewburn.vscode-intelephense-client
        - redhat.vscode-yaml
github:
    prebuilds:
        master: true
        branches: true
        pullRequests: true
        pullRequestsFromForks: true
        addCheck: false
        addComment: false
        addBadge: true
